# Generated by Django 3.2.6 on 2021-08-26 06:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('children', 'Children')], max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('available_sizes', multiselectfield.db.fields.MultiSelectField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('picture', models.ImageField(upload_to=product.models.Product.name_file)),
                ('client_type', multiselectfield.db.fields.MultiSelectField(choices=[('men', 'Men'), ('women', 'Women'), ('children', 'Children')], max_length=18)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productspecifications')),
            ],
        ),
    ]
